"""工程4: optional generated storyboard panels (default OFF).

Backend contract: no permission field → the message route behaves
byte-identically to today (0 generation calls, text-only view). Under an
explicit granted permission the same route extends to panels riding the
proposal entries — max 3 per proposal, 1-2 proposals, Luna codex-exec
transport with U47 model verification, the same cumulative episode
budget (scope-tagged, never reset), partial failure without auto-retry,
stale-base 409s, and generated bytes that never enter the edit pipeline.

No test here touches the real codex CLI: the text LLM factory and the
generation factory are both faked (the test_consultation_api pattern).
"""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient

from services.episode_cockpit import api_consultation, consultation_store
from services.episode_cockpit.app import create_cockpit_app
from services.episode_cockpit.consultation_store import ConsultationBudgetLimits
from services.episode_cockpit.generation_call import (
    GenerationError,
    decode_panel_image,
    request_panel_image,
    verify_generation_model,
)
from services.job_runner.cas import apply_transition, current_job_state
from services.job_runner.state_store import StateStore
from services.job_runner.transitions import MAIN_PATH

_DETAILS = {
    "audience_message": "始めて見る人に分かる導入",
    "structure": "導入→本編→締め",
    "duration_estimate": "約4分",
    "candidate_scenes": ["opening", "demo"],
    "subtitle_policy": "短めの字幕",
    "audio_policy": "BGM小さめ",
    "tempo_policy": "前半テンポ重視",
    "reference_mapping": "参考1の構成を踏襲",
    "unused_reasons": "未使用素材はなし",
    "unconfirmed": ["尺の希望"],
    "presentation_condition": "normal",
}

_TODAY_KEYS = {
    "consultation_id", "created_at", "message", "proposals", "judgments",
    "budget", "policy", "rebuild", "policy_outcomes",
}

_FAKE_MODEL = "gpt-5.6-sol"
_FAKE_PNG = b"\x89PNG\r\n\x1a\n" + b"\x00" * 32


def _envelope(count: int) -> dict[str, object]:
    return {
        "proposals": [
            {
                "title": f"案{i}",
                "summary": f"要旨{i}",
                "details": dict(_DETAILS),
            }
            for i in range(1, count + 1)
        ]
    }


@pytest.fixture
def workspace(tmp_path: Path) -> dict[str, Path]:
    return {"state_store": tmp_path / "state.db", "episodes_root": tmp_path / "jobs"}


@pytest.fixture
def client(workspace: dict[str, Path]) -> Any:
    app = create_cockpit_app(
        state_store_path=workspace["state_store"],
        episodes_root=workspace["episodes_root"],
    )
    with TestClient(app) as test_client:
        yield test_client


@pytest.fixture
def source_folder(tmp_path: Path) -> Path:
    folder = tmp_path / "cam-a"
    folder.mkdir()
    (folder / "clip-001.mp4").write_bytes(b"fake-mp4-bytes")
    return folder


@pytest.fixture
def llm_calls(monkeypatch: pytest.MonkeyPatch) -> list[str]:
    calls: list[str] = []

    def factory() -> Any:
        def call(message: str) -> dict[str, object]:
            calls.append(message)
            return _envelope(1)

        return call

    monkeypatch.setattr(api_consultation, "build_consultation_llm_call", factory)
    return calls


class GenFake:
    """Fail-loud fake of the Luna generation factory (fail-loud sentinel)."""

    def __init__(self) -> None:
        self.calls: list[dict[str, Any]] = []
        self.build_calls = 0
        self.fail_on: set[int] = set()
        self.verified = True
        self.method = "model-echo-probe"
        self.reason: str | None = None
        self.model_selected: str | None = _FAKE_MODEL

    def transport(self, prompt: str, input_frame: Any, model: str) -> bytes:
        self.calls.append(
            {"prompt": prompt, "input_frame": input_frame, "model": model}
        )
        if len(self.calls) in self.fail_on:
            raise GenerationError("generation-failed", "injected panel failure")
        return _FAKE_PNG + str(len(self.calls)).encode("ascii")

    def build(self) -> Any:
        self.build_calls += 1
        return api_consultation.GenerationCall(
            transport=self.transport,
            model_selected=self.model_selected,
            verified=self.verified,
            method=self.method,
            reason=self.reason,
            probe_ran=True,
            probe_wall_seconds=0.0,
        )


@pytest.fixture
def gen_fake(monkeypatch: pytest.MonkeyPatch) -> GenFake:
    fake = GenFake()
    monkeypatch.setattr(api_consultation, "build_generation_call", fake.build)
    return fake


def _create_episode(client: TestClient, source_folder: Path) -> str:
    response = client.post(
        "/episodes",
        json={"source_folder": str(source_folder), "brief_text": "絵コンテ相談用"},
    )
    assert response.status_code == 200
    return str(response.json()["episode_id"])


def _post_message(
    client: TestClient, episode_id: str, body: dict[str, Any] | None = None
) -> Any:
    payload: dict[str, Any] = {"message": "落ち着いた感じにしたい"}
    if body is not None:
        payload.update(body)
    return client.post(
        f"/episodes/{episode_id}/consultation/message", json=payload
    )


def _gen_ask(
    permission: dict[str, Any], specs: list[dict[str, Any]] | None = None
) -> dict[str, Any]:
    ask: dict[str, Any] = {"generation": {"permission": permission}}
    if specs is not None:
        ask["generation"]["panel_request"] = {"specs": specs}
    return ask


def _episode_dir(workspace: dict[str, Path], episode_id: str) -> Path:
    return workspace["episodes_root"] / episode_id


def _journal_lines(episode_dir: Path, *parts: str) -> list[bytes]:
    path = episode_dir.joinpath(*parts)
    try:
        return path.read_bytes().splitlines()
    except OSError:
        return []


# ---------------------------------------------------------------------------
# default OFF: byte-identity with today's contract
# ---------------------------------------------------------------------------


def test_default_off_message_is_byte_identical(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def _forbid(*_args: Any, **_kwargs: Any) -> Any:
        raise AssertionError("generation factory contacted without permission")

    monkeypatch.setattr(api_consultation, "build_generation_call", _forbid)
    episode_id = _create_episode(client, source_folder)

    response = _post_message(client, episode_id)

    assert response.status_code == 200
    body = response.json()
    assert set(body) == _TODAY_KEYS
    assert "panels" not in body
    assert "generation" not in body
    assert body["budget"]["llm_calls_used"] == 1
    assert "image_calls_used" not in body["budget"]
    episode_dir = _episode_dir(workspace, episode_id)
    assert _journal_lines(episode_dir, "consultation", "panels.jsonl") == []
    assert _journal_lines(episode_dir, "consultation", "generation.jsonl") == []


def test_get_list_without_generation_has_no_new_keys(
    client: TestClient, source_folder: Path, llm_calls: list[str]
) -> None:
    episode_id = _create_episode(client, source_folder)
    _post_message(client, episode_id)

    listed = client.get(f"/episodes/{episode_id}/consultation")

    assert listed.status_code == 200
    assert set(listed.json()["consultations"][0]) == _TODAY_KEYS


def test_ungranted_permission_keeps_text_with_honest_note(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    response = _post_message(
        client, episode_id,
        _gen_ask({"granted": False, "panels_max": 2, "images_max": 2}),
    )

    assert response.status_code == 200
    body = response.json()
    assert len(body["proposals"]) == 1
    assert body.get("panels", []) == []
    assert body["generation"]["decision"] == "refused"
    assert body["generation"]["reason"] == "generation-permission-not-granted"
    assert gen_fake.build_calls == 0
    assert gen_fake.calls == []


# ---------------------------------------------------------------------------
# U32: max 3 per proposal, 1-2 proposals, panel fields
# ---------------------------------------------------------------------------


def test_u32_message_panels_fields_and_two_proposal_spread(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    gen_fake: GenFake,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    seen: list[str] = []

    def factory() -> Any:
        def call(message: str) -> dict[str, object]:
            seen.append(message)
            return _envelope(2)

        return call

    monkeypatch.setattr(api_consultation, "build_consultation_llm_call", factory)
    episode_id = _create_episode(client, source_folder)

    response = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 4},
            [{"subject": "冒頭", "changes": "大テロップ"}, {"subject": "締め"}],
        ),
    )

    assert response.status_code == 200
    body = response.json()
    assert len(body["proposals"]) == 2
    assert len(body["panels"]) == 4
    by_proposal: dict[str, list[dict[str, Any]]] = {}
    for panel in body["panels"]:
        by_proposal.setdefault(panel["proposal_id"], []).append(panel)
    assert set(by_proposal) == {"prop-1", "prop-2"}
    for panels in by_proposal.values():
        assert len(panels) == 2
    first = body["panels"][0]
    assert set(first) == {
        "panel_id", "proposal_id", "role", "kind", "kind_label_ja",
        "source_frame_ref", "image_ref", "caption", "status",
        "error_code", "model_selected", "base_created_at", "created_at",
    }
    assert first["role"] == "a"
    assert first["kind"] == "generated"
    assert first["kind_label_ja"] == "生成した見た目の案"
    assert first["status"] == "generated"
    assert first["error_code"] is None
    assert first["model_selected"] == _FAKE_MODEL
    assert first["caption"]["subject"] == "冒頭"
    assert first["caption"]["unconfirmed"] != []
    assert first["image_ref"].endswith(".png")
    assert len(gen_fake.calls) == 4
    assert body["generation"]["verified"] is True
    assert body["generation"]["model_selected"] == _FAKE_MODEL
    assert body["budget"]["image_calls_used"] == 4
    episode_dir = _episode_dir(workspace, episode_id)
    for panel in body["panels"]:
        assert (episode_dir / panel["image_ref"]).is_file()


def test_u32_scope_refusal_is_zero_call(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    response = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 4},
            [{"subject": "a"}, {"subject": "b"}, {"subject": "c"}],
        ),
    )

    assert response.status_code == 200
    body = response.json()
    assert len(body["proposals"]) == 1
    assert body.get("panels", []) == []
    assert body["generation"]["decision"] == "refused"
    assert body["generation"]["reason"] == "generation-out-of-scope"
    assert gen_fake.build_calls == 0
    assert gen_fake.calls == []
    assert body["budget"]["llm_calls_used"] == 1


def test_u32_vague_ask_is_zero_call(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    response = _post_message(
        client, episode_id,
        {"generation": {"permission": {
            "granted": True, "panels_max": 2, "images_max": 2,
        }}},
    )

    assert response.status_code == 200
    assert response.json()["generation"]["reason"] == "generation-needs-confirmation"
    assert gen_fake.build_calls == 0
    assert gen_fake.calls == []


# ---------------------------------------------------------------------------
# U40: same-frame A/B inputs ride -i together
# ---------------------------------------------------------------------------


def test_u40_same_frame_ab_inputs(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)
    episode_dir = _episode_dir(workspace, episode_id)
    frames = episode_dir / "review-frames"
    frames.mkdir(parents=True, exist_ok=True)
    still = frames / "frame-000.jpg"
    still.write_bytes(b"fake-still")
    ref = "review-frames/frame-000.jpg"

    response = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 2},
            [
                {"frame_ref": ref, "role": "a", "changes": "大テロップ"},
                {"frame_ref": ref, "role": "b", "changes": "控えめ"},
            ],
        ),
    )

    assert response.status_code == 200
    assert [p["role"] for p in response.json()["panels"]] == ["a", "b"]
    assert len(gen_fake.calls) == 2
    assert gen_fake.calls[0]["input_frame"] == still
    assert gen_fake.calls[1]["input_frame"] == still
    assert gen_fake.calls[0]["model"] == _FAKE_MODEL


# ---------------------------------------------------------------------------
# U33/U37: partial failure, explicit retry only, no auto-retry
# ---------------------------------------------------------------------------


def test_u33_partial_retry_keeps_other_panels(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    gen_fake: GenFake,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    limits = ConsultationBudgetLimits(
        llm_calls_limit=12, intervals_limit=6, wall_seconds_limit=600.0
    )
    monkeypatch.setattr(api_consultation, "load_budget_limits", lambda: limits)

    def text_factory() -> Any:
        def call(message: str) -> dict[str, object]:
            return _envelope(1)

        return call

    monkeypatch.setattr(
        api_consultation, "build_consultation_llm_call", text_factory
    )
    gen_fake.fail_on = {2}
    episode_id = _create_episode(client, source_folder)

    first = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 3, "images_max": 3},
            [{"subject": "one"}, {"subject": "two"}, {"subject": "three"}],
        ),
    )

    assert first.status_code == 200
    panels = first.json()["panels"]
    assert [p["status"] for p in panels] == ["generated", "failed", "generated"]
    assert len(gen_fake.calls) == 3  # one attempt each: never auto-retried
    failed_id = panels[1]["panel_id"]
    kept = {p["panel_id"]: p["image_ref"] for p in (panels[0], panels[2])}
    kept_bytes = {
        pid: (_episode_dir(workspace, episode_id) / ref).read_bytes()
        for pid, ref in kept.items()
    }
    base = panels[0]["base_created_at"]

    retry = client.post(
        f"/episodes/{episode_id}/consultation/panels",
        json={
            "consultation_id": first.json()["consultation_id"],
            "proposal_id": "prop-1",
            "base_created_at": base,
            "permission": {"granted": True, "panels_max": 3, "images_max": 1},
            "retry_panel_ids": [failed_id],
        },
    )

    assert retry.status_code == 200
    after = {p["panel_id"]: p for p in retry.json()["panels"]}
    assert after[failed_id]["status"] == "generated"
    assert after[failed_id]["image_ref"] is not None
    assert len(gen_fake.calls) == 4  # exactly one more attempt
    for pid, ref in kept.items():
        assert after[pid]["image_ref"] == ref
        assert (_episode_dir(workspace, episode_id) / ref).read_bytes() == kept_bytes[pid]


def test_u37_failed_spend_is_ledgered_and_never_reset(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    gen_fake.fail_on = {1}
    episode_id = _create_episode(client, source_folder)
    episode_dir = _episode_dir(workspace, episode_id)

    first = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    )

    assert first.json()["panels"][0]["status"] == "failed"
    assert first.json()["panels"][0]["error_code"] == "generation-failed"
    failures = [
        json.loads(line) for line in
        _journal_lines(episode_dir, "consultation", "budget.jsonl")
        if json.loads(line)["failure_code"] == "generation-failed"
    ]
    assert len(failures) == 1
    assert failures[0]["kind"] == "image"
    assert failures[0]["llm_calls"] == 1
    used_before = first.json()["budget"]["llm_calls_used"]

    _post_message(client, episode_id)

    listed = client.get(f"/episodes/{episode_id}/consultation")
    last = listed.json()["consultations"][-1]
    assert last["budget"]["llm_calls_used"] == used_before + 1
    assert len(_journal_lines(episode_dir, "consultation", "budget.jsonl")) > len(
        _journal_lines(episode_dir, "consultation", "budget.jsonl")[:0]
    )


def test_u37_success_and_failure_share_the_cumulative_ledger(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    gen_fake.fail_on = {2}
    episode_id = _create_episode(client, source_folder)

    body = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 2},
            [{"subject": "one"}, {"subject": "two"}],
        ),
    ).json()

    # text(1) + probe(1) + images(2, one failed but still spent)
    assert body["budget"]["llm_calls_used"] == 4
    assert body["budget"]["image_calls_used"] == 2
    assert body["budget"]["intervals_used"] == 1


# ---------------------------------------------------------------------------
# U35: 区分 labels in view
# ---------------------------------------------------------------------------


def test_u35_kind_labels_distinguish_real_and_generated(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)
    episode_dir = _episode_dir(workspace, episode_id)
    frames = episode_dir / "review-frames"
    frames.mkdir(parents=True, exist_ok=True)
    (frames / "frame-000.jpg").write_bytes(b"fake-still")

    body = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 1},
            [
                {"frame_ref": "review-frames/frame-000.jpg", "role": "real_frame"},
                {"subject": "生成案"},
            ],
        ),
    ).json()

    assert body["panels"][0]["kind"] == "real_frame"
    assert body["panels"][0]["kind_label_ja"] == "撮影素材"
    assert body["panels"][0]["image_ref"] is None
    assert body["panels"][0]["status"] is None
    assert len(gen_fake.calls) == 1  # real frames never call the seam
    assert body["panels"][1]["kind"] == "generated"
    assert body["panels"][1]["kind_label_ja"] == "生成した見た目の案"


# ---------------------------------------------------------------------------
# U34: judgment with panels leaves the rebuild flow unchanged
# ---------------------------------------------------------------------------


def test_u34_judgment_with_panels_never_leaks_into_policy(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)
    episode_dir = _episode_dir(workspace, episode_id)
    with StateStore.open(workspace["state_store"]) as store:
        while True:
            current = current_job_state(store, episode_id)
            position = MAIN_PATH.index(current.status)
            if position >= MAIN_PATH.index("PREVIEW_READY"):
                break
            apply_transition(
                store,
                episode_id,
                expected_status=current.status,
                expected_parent_hash=current.adopted_artifact_hash,
                new_status=MAIN_PATH[position + 1],
                new_artifact_hash="0" * 64,
                payload=None,
            )

    created = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()
    consultation_id = created["consultation_id"]
    assert len(created["panels"]) == 1

    judged = client.post(
        f"/episodes/{episode_id}/consultation/judgment",
        json={
            "consultation_id": consultation_id,
            "proposal_id": "prop-1",
            "decision": "adopt",
            "scope": {"composition": True, "appearance": False, "audio": False},
            "note": None,
        },
    )

    assert judged.status_code in (200, 202)
    policy = consultation_store.latest_adopted_policy(episode_dir)
    assert policy is not None
    dumped = json.dumps(policy.model_dump(mode="json"), ensure_ascii=False)
    assert "pnl-" not in dumped
    assert "consultation/panels" not in dumped
    assert "image_ref" not in dumped
    summary = consultation_store.policy_summary(policy)
    assert "pnl-" not in json.dumps(summary.model_dump(mode="json"))
    for proposal in judged.json()["proposals"]:
        assert "panels" not in proposal
    for entry in consultation_store.load_policy_rebuild_entries(episode_dir):
        assert "pnl-" not in json.dumps(entry.model_dump(mode="json"))


# ---------------------------------------------------------------------------
# U38: stale re-request refused
# ---------------------------------------------------------------------------


def test_u38_stale_retry_is_409_with_zero_calls(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    gen_fake.fail_on = {1}
    episode_id = _create_episode(client, source_folder)
    episode_dir = _episode_dir(workspace, episode_id)

    first = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()
    old_base = first["panels"][0]["base_created_at"]
    failed_id = first["panels"][0]["panel_id"]
    lines_before = len(_journal_lines(episode_dir, "consultation", "panels.jsonl"))

    # Move the proposal base the append-only way (a regenerated set
    # supersedes the old table); the old base must then refuse.
    moved = consultation_store.ConsultationProposalSetV1(
        consultation_id=first["consultation_id"],
        created_at=consultation_store.now_stamp(),
        proposals=tuple(
            consultation_store.ConsultationProposalV1.model_validate(p)
            for p in first["proposals"]
        ),
    )
    assert moved.created_at != old_base
    consultation_store.append_proposal_set(episode_dir, moved)
    gen_fake.fail_on = set()
    calls_before = len(gen_fake.calls)

    stale = client.post(
        f"/episodes/{episode_id}/consultation/panels",
        json={
            "consultation_id": first["consultation_id"],
            "proposal_id": "prop-1",
            "base_created_at": old_base,
            "permission": {"granted": True, "panels_max": 1, "images_max": 1},
            "retry_panel_ids": [failed_id],
        },
    )

    assert stale.status_code == 409
    assert stale.json()["error"]["code"] == "generation-stale"
    assert len(gen_fake.calls) == calls_before
    assert len(_journal_lines(episode_dir, "consultation", "panels.jsonl")) == lines_before


def test_u38_unknown_panel_is_typed_422(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)
    created = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()
    base = created["panels"][0]["base_created_at"]

    response = client.post(
        f"/episodes/{episode_id}/consultation/panels",
        json={
            "consultation_id": created["consultation_id"],
            "proposal_id": "prop-1",
            "base_created_at": base,
            "permission": {"granted": True, "panels_max": 1, "images_max": 1},
            "retry_panel_ids": ["pnl-missing"],
        },
    )

    assert response.status_code == 422
    assert response.json()["error"]["code"] == "consultation-panel-not-found"


# ---------------------------------------------------------------------------
# U45: refusal and limits — zero generation calls, main route unaffected
# ---------------------------------------------------------------------------


def test_u45_exhausted_budget_refuses_before_any_generation_call(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    limits = ConsultationBudgetLimits(
        llm_calls_limit=1, intervals_limit=3, wall_seconds_limit=600.0
    )
    monkeypatch.setattr(api_consultation, "load_budget_limits", lambda: limits)
    episode_id = _create_episode(client, source_folder)

    response = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    )

    assert response.status_code == 200
    body = response.json()
    assert len(body["proposals"]) == 1  # the text consultation stands
    assert body.get("panels", []) == []
    assert body["generation"]["decision"] == "refused"
    assert gen_fake.build_calls == 0
    assert gen_fake.calls == []


def test_u45_gated_transport_continues_text_only(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def gated_build() -> Any:
        gen_fake.build_calls += 1
        return api_consultation.GenerationCall(
            transport=None, model_selected=None, verified=False,
            method="transport-gated", reason="codex CLI is not on PATH",
            probe_ran=False, probe_wall_seconds=0.0,
        )

    monkeypatch.setattr(api_consultation, "build_generation_call", gated_build)
    episode_id = _create_episode(client, source_folder)

    body = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()

    assert len(body["proposals"]) == 1
    assert body.get("panels", []) == []
    assert body["generation"]["reason"] == "generation-model-unverified"
    assert gen_fake.calls == []


# ---------------------------------------------------------------------------
# U46: out-of-scope asks wait for re-confirmation; budget never resets
# ---------------------------------------------------------------------------


def test_u46_out_of_scope_waits_for_reconfirmation(
    client: TestClient,
    source_folder: Path,
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    refused = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 1},
            [{"subject": "one"}, {"subject": "two"}],
        ),
    ).json()

    assert refused.get("panels", []) == []
    assert refused["generation"]["reason"] == "generation-out-of-scope"
    assert gen_fake.calls == []
    assert refused["budget"]["llm_calls_used"] == 1  # text only; nothing reset

    confirmed = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 2, "images_max": 2},
            [{"subject": "one"}, {"subject": "two"}],
        ),
    ).json()

    assert len(confirmed["panels"]) == 2
    assert len(gen_fake.calls) == 2
    assert confirmed["budget"]["llm_calls_used"] > refused["budget"]["llm_calls_used"]


# ---------------------------------------------------------------------------
# U47: model verification gates every image call and is journaled
# ---------------------------------------------------------------------------


def test_u47_unverified_model_is_zero_call_and_journaled(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    gen_fake.verified = False
    gen_fake.method = "model-echo-mismatch"
    gen_fake.reason = "the selected model did not confirm 'gpt-5.6-sol'"
    episode_id = _create_episode(client, source_folder)

    body = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()

    assert len(body["proposals"]) == 1
    assert body.get("panels", []) == []
    assert body["generation"]["verified"] is False
    assert body["generation"]["reason"] == "generation-model-unverified"
    assert gen_fake.calls == []
    events = consultation_store.load_generation_events(
        _episode_dir(workspace, episode_id), body["consultation_id"]
    )
    assert events[-1].verified is False
    assert events[-1].decision == "refused"


def test_u47_verified_model_is_recorded_in_journal(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    body = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()

    assert body["generation"]["verified"] is True
    assert body["generation"]["model_selected"] == _FAKE_MODEL
    events = consultation_store.load_generation_events(
        _episode_dir(workspace, episode_id), body["consultation_id"]
    )
    assert events[-1].model_selected == _FAKE_MODEL
    assert events[-1].verified is True


def test_u47_verify_generation_model_unit() -> None:
    verified = verify_generation_model(
        transport="codex-exec", model_pin=_FAKE_MODEL,
        probe=lambda: f"running as {_FAKE_MODEL} here",
    )
    assert verified.verified is True
    assert verified.model_selected == _FAKE_MODEL

    assert verify_generation_model(
        transport="codex-exec", model_pin=_FAKE_MODEL, probe=None
    ).verified is False

    assert verify_generation_model(
        transport="codex-exec", model_pin=_FAKE_MODEL,
        probe=lambda: "some other model",
    ).verified is False

    def _boom() -> str:
        raise RuntimeError("preflight down")

    assert verify_generation_model(
        transport="codex-exec", model_pin=_FAKE_MODEL, probe=_boom
    ).verified is False

    assert verify_generation_model(
        transport="openai-api", model_pin=_FAKE_MODEL,
        probe=lambda: _FAKE_MODEL,
    ).verified is False

    assert verify_generation_model(
        transport="codex-exec", model_pin=None, probe=lambda: "x"
    ).verified is False


def test_u47_request_panel_image_refusals_are_zero_call() -> None:
    def _forbid(prompt: str, input_frame: Any, model: str) -> bytes:
        raise AssertionError("transport contacted despite refusal")

    with pytest.raises(GenerationError) as exc:
        request_panel_image(
            prompt="p", input_frame=None, model="m", permission_granted=False,
            model_verified=True, transport=_forbid,
        )
    assert exc.value.code == "generation-permission-required"

    with pytest.raises(GenerationError) as exc:
        request_panel_image(
            prompt="p", input_frame=None, model="m", permission_granted=True,
            model_verified=False, transport=_forbid,
        )
    assert exc.value.code == "generation-model-unverified"

    with pytest.raises(GenerationError) as exc:
        request_panel_image(
            prompt="p", input_frame=None, model="m", permission_granted=True,
            model_verified=True, transport=None,
        )
    assert exc.value.code == "generation-transport-gated"


def test_usage_limit_maps_to_typed_error_without_retry() -> None:
    def _limited(prompt: str, input_frame: Any, model: str) -> bytes:
        raise RuntimeError("request hit the usage limit for this window")

    with pytest.raises(GenerationError) as exc:
        request_panel_image(
            prompt="p", input_frame=None, model="m", permission_granted=True,
            model_verified=True, transport=_limited,
        )
    assert exc.value.code == "generation-usage-limited"


def test_decode_panel_image_validates_payload() -> None:
    good = base64.b64encode(_FAKE_PNG).decode("ascii")
    assert decode_panel_image(json.dumps({"image_base64": good})) == _FAKE_PNG
    assert decode_panel_image(good) == _FAKE_PNG

    with pytest.raises(GenerationError) as exc:
        decode_panel_image("not-base64!!")
    assert exc.value.code == "generation-bad-image"

    bad = base64.b64encode(b"plain text, not an image").decode("ascii")
    with pytest.raises(GenerationError) as exc:
        decode_panel_image(bad)
    assert exc.value.code == "generation-bad-image"


# ---------------------------------------------------------------------------
# served panel bytes
# ---------------------------------------------------------------------------


def test_panel_file_serves_generated_bytes(
    client: TestClient,
    source_folder: Path,
    workspace: dict[str, Path],
    llm_calls: list[str],
    gen_fake: GenFake,
) -> None:
    episode_id = _create_episode(client, source_folder)

    created = _post_message(
        client, episode_id,
        _gen_ask(
            {"granted": True, "panels_max": 1, "images_max": 1},
            [{"subject": "only"}],
        ),
    ).json()
    panel_id = created["panels"][0]["panel_id"]

    served = client.get(
        f"/episodes/{episode_id}/consultation/panels/{panel_id}"
    )

    assert served.status_code == 200
    assert served.headers["content-type"] == "image/png"
    expected = (
        _episode_dir(workspace, episode_id) / created["panels"][0]["image_ref"]
    ).read_bytes()
    assert served.content == expected

    missing = client.get(f"/episodes/{episode_id}/consultation/panels/pnl-nope")
    assert missing.status_code == 404
    assert missing.json()["error"]["code"] == "consultation-panel-not-found"
